sonata_user:
  class:
    user: App\Entity\User
  resetting:
    email:
      address: sonata@localhost
      sender_name: Sonata Admin

  admin: # Admin Classes
    user:
      class: App\Admin\UserAdmin
      controller: App\Controller\Admin\UserAdminController
      translation: SonataUserBundle