App\Entity\User:
    type: entity
    table: user
    repositoryClass: App\Repository\UserRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    oneToMany:
        comments:
            targetEntity: App\Entity\Comment
            mappedBy: user
